name: CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fwilhe2/setup-kotlin@0.2.0
      
      - name: Setup Java JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: adopt
          java-version: 11
      
      - name: Make gradlew file executable
        run: chmod +x gradlew
      
      - name: Build application
        run: ./gradlew installDist
        
      - name: Make application executable
        run: chmod +x build/backend/bin/backend
      
      - name: Send built application to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "build/backend"
          target: "/tmp/destiny/"
          strip_components: 1
          
      - name: Send service file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "destiny.service"
          target: "/tmp"
      
      - name: Run server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo rm -Rf /opt/destiny
            sudo mv /tmp/destiny /opt
            sudo rm -f /etc/systemd/system/destiny.service
            sudo mv /tmp/destiny.service /etc/systemd/system/destiny.service
            sudo systemctl daemon-reload
            sudo systemctl restart destiny.service
            sudo rm -Rf /tmp/destiny
            sudo rm -f /tmp/destiny.service
